### ISSUE TITLE
Error ReferenceError: self is not defined

### ISSUE THREAD

**Issue by davidqhr** [shakacode/react-webpack-rails-tutorial#248]
I got the error when server rendering. Any help will be appreciated
```
14:14:22 rails.1               | ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
14:14:22 rails.1               | react_renderer.rb: 92
14:14:22 rails.1               | wrote file tmp/base_js_code.js
14:14:22 rails.1               | ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
14:14:22 rails.1               |   Rendered react/index.html.erb within layouts/brand (893.7ms)
14:14:22 rails.1               | ERROR in SERVER PRERENDERING
14:14:22 rails.1               | Encountered error: "ReferenceError: self is not defined"
14:14:22 rails.1               | when prerendering BrandApp with props: {"current_uesr":{"name":"david","guid":"XXXXX-XXXXXX-XXXX"}}
14:14:22 rails.1               | js_code was:
14:14:22 rails.1               | (function() {
14:14:22 rails.1               |
14:14:22 rails.1               |   var props = {"current_uesr":{"name":"david","guid":"XXXXX-XXXXXX-XXXX"}};
14:14:22 rails.1               |   return ReactOnRails.serverRenderReactComponent({
14:14:22 rails.1               |     name: 'BrandApp',
14:14:22 rails.1               |     domNodeId: 'BrandApp-react-component-0',
14:14:22 rails.1               |     props: props,
14:14:22 rails.1               |     trace: true,
14:14:22 rails.1               |     location: '/react'
14:14:22 rails.1               |   });
14:14:22 rails.1               | })()
14:14:22 rails.1               |
14:14:22 rails.1               |
14:14:22 rails.1               | Object.<anonymous> ((execjs):59433:19)
14:14:22 rails.1               | __webpack_require__ ((execjs):39:30)
14:14:22 rails.1               | Object.defineProperty.value ((execjs):7645:2)
14:14:22 rails.1               | __webpack_require__ ((execjs):39:30)
14:14:22 rails.1               | Object.<anonymous> ((execjs):67:19)
14:14:22 rails.1               | __webpack_require__ ((execjs):39:30)
14:14:22 rails.1               | (execjs):59:18
14:14:22 rails.1               | (execjs):62:10
14:14:22 rails.1               | (execjs):59840:14
14:14:22 rails.1               | console.history ((execjs):1:102)
14:14:22 rails.1               | /Users/david/.rvm/gems/ruby-2.2.2@robin8/gems/execjs-2.5.2/lib/execjs/external_runtime.rb:39:in `exec'
14:14:22 rails.1               | /Users/david/.rvm/gems/ruby-2.2.2@robin8/gems/execjs-2.5.2/lib/execjs/external_runtime.rb:14:in `initialize'
14:14:22 rails.1               | /Users/david/.rvm/gems/ruby-2.2.2@robin8/gems/execjs-2.5.2/lib/execjs/runtime.rb:44:in `new'
14:14:22 rails.1               | /Users/david/.rvm/gems/ruby-2.2.2@robin8/gems/execjs-2.5.2/lib/execjs/runtime.rb:44:in `compile'
14:14:22 rails.1               | /Users/david/.rvm/gems/ruby-2.2.2@robin8/gems/execjs-2.5.2/lib/execjs/module.rb:27:in `compile'
```

**Comment by justin808** [comment]
Try turning prerendering off, then debug in the browser.
