### ISSUE TITLE
Fix issues with Redis

### ISSUE THREAD

**Issue by ahangarha** [shakacode/react-webpack-rails-tutorial#558]
There is such error in the console when one submits a comment:

```
rails     | [ActiveJob] [CommentRelayJob] [7c424d94-ce31-4705-be87-76e42a563d8b] Error performing CommentRelayJob (Job ID: 7c424d94-ce31-4705-be87-76e42a563d8b) from Async(default) in 11.3ms: Gem::LoadError (Error loading the 'redis' Action Cable pubsub adapter. Missing a gem it depends on? can't activate redis (>= 4, < 6), already activated redis-3.3.3. Make sure all dependencies are added to Gemfile.):
```
We need to upgrade radis (ruby gem) to 4+.

Also there is an error related to redis when we delete a comment:

```
rails     | Started DELETE "/comments/347" for 127.0.0.1 at 2023-10-15 23:27:45 +0330
rails     | Processing by CommentsController#destroy as TURBO_STREAM
rails     |   Parameters: {"authenticity_token"=>"[FILTERED]", "id"=>"347"}
rails     |   Comment Load (0.8ms)  SELECT "comments".* FROM "comments" WHERE "comments"."id" = $1 LIMIT $2  [["id", 347], ["LIMIT", 1]]
rails     |   ↳ app/controllers/comments_controller.rb:110:in `set_comment'
rails     |   TRANSACTION (0.1ms)  BEGIN
rails     |   ↳ app/controllers/comments_controller.rb:64:in `destroy'
rails     |   Comment Destroy (1.7ms)  DELETE FROM "comments" WHERE "comments"."id" = $1  [["id", 347]]
rails     |   ↳ app/controllers/comments_controller.rb:64:in `destroy'
rails     |   TRANSACTION (1.9ms)  COMMIT
rails     |   ↳ app/controllers/comments_controller.rb:64:in `destroy'
rails     | [ActiveJob] Enqueued CommentRelayJob (Job ID: c1058e00-0ab7-434f-a5e2-6922006b3e66) to Async(default) with arguments: #<GlobalID:0x00007f3a6350b4b0 @uri=#<URI::GID gid://rails-react-tutorial/Comment/347>>
rails     | Redirected to http://127.0.0.1:3000/comments
rails     | Completed 302 Found in 11ms (ActiveRecord: 4.4ms | Allocations: 3549)
rails     | 
rails     | 
rails     | [ActiveJob] [CommentRelayJob] [c1058e00-0ab7-434f-a5e2-6922006b3e66]   Comment Load (0.6ms)  SELECT "comments".* FROM "comments" WHERE "comments"."id" = $1 LIMIT $2  [["id", 347], ["LIMIT", 1]]
rails     | [ActiveJob] [CommentRelayJob] [c1058e00-0ab7-434f-a5e2-6922006b3e66] Error performing CommentRelayJob (Job ID: c1058e00-0ab7-434f-a5e2-6922006b3e66) from Async(default) in 5.63ms: ActiveJob::DeserializationError (Error while trying to deserialize arguments: Couldn't find Comment with 'id'=347):
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.1.1/lib/active_record/relation/finder_methods.rb:416:in `raise_record_not_found_exception!'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.1.1/lib/active_record/relation/finder_methods.rb:522:in `find_one'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.1.1/lib/active_record/relation/finder_methods.rb:499:in `find_with_ids'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.1.1/lib/active_record/relation/finder_methods.rb:92:in `find'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.1.1/lib/active_record/querying.rb:23:in `find'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.1.1/lib/active_record/core.rb:245:in `find'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/globalid-1.1.0/lib/global_id/locator.rb:129:in `locate'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/globalid-1.1.0/lib/global_id/locator.rb:154:in `block in locate'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/globalid-1.1.0/lib/global_id/locator.rb:164:in `block in unscoped'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.1.1/lib/active_record/relation.rb:914:in `_scoping'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.1.1/lib/active_record/relation.rb:452:in `scoping'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.1.1/lib/active_record/scoping/default.rb:51:in `unscoped'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/globalid-1.1.0/lib/global_id/locator.rb:164:in `unscoped'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/globalid-1.1.0/lib/global_id/locator.rb:154:in `locate'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/globalid-1.1.0/lib/global_id/locator.rb:16:in `locate'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activejob-7.1.1/lib/active_job/arguments.rb:137:in `deserialize_global_id'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activejob-7.1.1/lib/active_job/arguments.rb:121:in `deserialize_argument'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activejob-7.1.1/lib/active_job/arguments.rb:43:in `block in deserialize'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activejob-7.1.1/lib/active_job/arguments.rb:43:in `map'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activejob-7.1.1/lib/active_job/arguments.rb:43:in `deserialize'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activejob-7.1.1/lib/active_job/core.rb:210:in `deserialize_arguments'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activejob-7.1.1/lib/active_job/core.rb:200:in `deserialize_arguments_if_needed'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activejob-7.1.1/lib/active_job/execution.rb:50:in `perform_now'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activejob-7.1.1/lib/active_job/instrumentation.rb:26:in `block in perform_now'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.1.1/lib/active_record/railties/job_runtime.rb:13:in `block in instrument'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activejob-7.1.1/lib/active_job/instrumentation.rb:40:in `block in instrument'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.1.1/lib/active_support/notifications.rb:206:in `block in instrument'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.1.1/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.1.1/lib/active_support/notifications.rb:206:in `instrument'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activejob-7.1.1/lib/active_job/instrumentation.rb:39:in `instrument'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.1.1/lib/active_record/railties/job_runtime.rb:11:in `instrument'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activejob-7.1.1/lib/active_job/instrumentation.rb:26:in `perform_now'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activejob-7.1.1/lib/active_job/logging.rb:18:in `block in perform_now'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.1.1/lib/active_support/tagged_logging.rb:135:in `block in tagged'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.1.1/lib/active_support/tagged_logging.rb:39:in `tagged'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.1.1/lib/active_support/tagged_logging.rb:135:in `tagged'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.1.1/lib/active_support/broadcast_logger.rb:232:in `method_missing'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activejob-7.1.1/lib/active_job/logging.rb:25:in `tag_logger'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activejob-7.1.1/lib/active_job/logging.rb:18:in `perform_now'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activejob-7.1.1/lib/active_job/execution.rb:30:in `block in execute'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.1.1/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activejob-7.1.1/lib/active_job/railtie.rb:67:in `block (4 levels) in <class:Railtie>'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.1.1/lib/active_support/reloader.rb:77:in `block in wrap'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.1.1/lib/active_support/execution_wrapper.rb:92:in `wrap'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.1.1/lib/active_support/reloader.rb:74:in `wrap'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activejob-7.1.1/lib/active_job/railtie.rb:66:in `block (3 levels) in <class:Railtie>'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.1.1/lib/active_support/callbacks.rb:130:in `instance_exec'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.1.1/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.1.1/lib/active_support/callbacks.rb:141:in `run_callbacks'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activejob-7.1.1/lib/active_job/execution.rb:28:in `execute'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activejob-7.1.1/lib/active_job/queue_adapters/async_adapter.rb:70:in `perform'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `run_task'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:343:in `block (3 levels) in create_worker'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `loop'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block (2 levels) in create_worker'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `catch'
rails     | /home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `block in create_worker'
```

**Comment by ahangarha** [comment]
This issue started since Upgrading to Rails 7.1 in 9c3bb2e.
